ctrl_interface=/var/run/hostapd
ctrl_interface_group=0

interface=wlan14
driver=nl80211
ssid=TETANGGA SEBELAH
hw_mode=g
channel=9
country_code=ID
auth_algs=1
wpa=3
wpa_passphrase=1234567890
wpa_key_mgmt=WPA-PSK
wpa_pairwise=TKIP
rsn_pairwise=CCMP
