# ------------------------------------------------------------------------------------------------
#
# Lab Virtual Wireless Hacking (https://github.com/fixploit03/Lab-Virtual-Wireless-Hacking/)
#
# ------------------------------------------------------------------------------------------------
#
# wifi opn
interface=wlan2
# wifi wpa-personal
interface=wlan6
# wifi wpa2-personal
interface=wlan10
# wifi wpa/wpa2-personal
interface=wlan14
# wifi wpa2-enterprise
interface=wlan18
# wifi wpa3-transition mode
interface=wlan22
# wifi wpa3-sae
interface=wlan26

bind-interfaces

# dhcp range
dhcp-range=wlan2,10.10.1.2,10.10.1.254,255.255.255.0,12h
dhcp-range=wlan6,10.10.10.2,10.10.10.254,255.255.255.0,12h
dhcp-range=wlan10,10.10.20.2,10.10.20.254,255.255.255.0,12h
dhcp-range=wlan14,10.10.30.2,10.10.30.254,255.255.255.0,12h
dhcp-range=wlan18,10.10.40.2,10.10.40.254,255.255.255.0,12h
dhcp-range=wlan22,10.10.50.2,10.10.50.254,255.255.255.0,12h
dhcp-range=wlan26,10.10.60.2,10.10.60.254,255.255.255.0,12h

# gateway
dhcp-option=tag:wlan2,3,10.10.1.1
dhcp-option=tag:wlan6,3,10.10.10.1
dhcp-option=tag:wlan10,3,10.10.20.1
dhcp-option=tag:wlan14,3,10.10.30.1
dhcp-option=tag:wlan18,3,10.10.40.1
dhcp-option=tag:wlan22,3,10.10.50.1
dhcp-option=tag:wlan26,3,10.10.60.1

# disable dns
port=0
# log dhcp
log-dhcp
