ctrl_interface=/var/run/hostapd
ctrl_interface_group=0

interface=wlan22
driver=nl80211
ssid=Angkringan BG Yanto
hw_mode=g
channel=5
country_code=ID
auth_algs=1
wpa=2
wpa_passphrase=rahasiadong
sae_password=rahasiadong
wpa_key_mgmt=WPA-PSK SAE
rsn_pairwise=CCMP
ieee80211w=1
