ctrl_interface=/var/run/wpa_supplicant
ctrl_interface_group=0

network={
        ssid="Angkringan BG Yanto"
        key_mgmt=WPA-PSK SAE
        psk="rahasiadong"
        sae_password="rahasiadong"
}
